/* ipc_config.h — Zephyr port IPC configuration shim. */
#pragma once

#include <zephyr/sys/util.h>

#define IPC_CORE_MAX_REGISTRATIONS CONFIG_ACTOR_MAX_REGISTRATIONS
#define IPC_CORE_MAX_SUBSCRIPTIONS CONFIG_ACTOR_MAX_SUBSCRIPTIONS
#if defined(CONFIG_ACTOR_ASK)
#define IPC_CORE_MAX_INFLIGHT_QUERIES CONFIG_ACTOR_MAX_INFLIGHT_ASKS
#define IPC_CONFIG_ENABLE_ASK 1
#else
#define IPC_CORE_MAX_INFLIGHT_QUERIES 1
#define IPC_CONFIG_ENABLE_ASK 0
#endif

#if defined(CONFIG_ACTOR_DIAGNOSTICS)
#define IPC_CONFIG_ENABLE_DIAGNOSTICS 1
#else
#define IPC_CONFIG_ENABLE_DIAGNOSTICS 0
#endif

BUILD_ASSERT(CONFIG_ACTOR_MAX_REGISTRATIONS > 0,
             "CONFIG_ACTOR_MAX_REGISTRATIONS must be greater than zero");
BUILD_ASSERT(CONFIG_ACTOR_MAX_SUBSCRIPTIONS >= 0,
             "CONFIG_ACTOR_MAX_SUBSCRIPTIONS must be non-negative");
#if defined(CONFIG_ACTOR_ASK)
BUILD_ASSERT(CONFIG_ACTOR_MAX_INFLIGHT_ASKS > 0,
             "CONFIG_ACTOR_MAX_INFLIGHT_ASKS must be greater than zero");
BUILD_ASSERT(CONFIG_ACTOR_MAX_PENDING_ASK_TIMEOUTS > 0,
             "CONFIG_ACTOR_MAX_PENDING_ASK_TIMEOUTS must be greater than zero");
BUILD_ASSERT(
    CONFIG_ACTOR_MAX_PENDING_ASK_TIMEOUTS <= CONFIG_ACTOR_MAX_INFLIGHT_ASKS,
    "CONFIG_ACTOR_MAX_PENDING_ASK_TIMEOUTS must not exceed CONFIG_ACTOR_MAX_INFLIGHT_ASKS");
#endif
